"""Help 插件源代码"""

from .application import (
    CommandDetailResponse,
    CustomGroupService,
    ExecuteCommandResponse,
    HelpService,
    ListCustomGroupsResponse,
    SearchCommandResponse,
    get_help_service,
    get_custom_group_service,
    init_plugin_service,
    reset_help_service,
    reset_custom_group_service,
)
from .domain import (
    CommandEntry,
    MatchedHandlerInfo,
    PluginCommandSummary,
)
from .infrastructure import (
    CommandExecutor,
    CommandIndex,
    clear_context,
    get_cache_dir,
    get_command_executor,
    get_command_index,
    get_context,
    get_custom_groups_path,
    get_data_dir,
    get_logger,
    get_plugin_data_dir,
    get_plugin_dir,
    init_plugin_paths,
    invalidate_command_cache,
    logger,
    set_context,
)
from .infrastructure.config import (
    CustomGroupCommand,
    CustomGroupConfig,
    HelpPluginConfig,
    get_config,
    init_config,
    refresh_config,
    save_custom_groups_to_storage,
    update_custom_groups_in_config,
)

__all__ = [
    # Domain
    "HelpPluginConfig",
    "CustomGroupCommand",
    "CustomGroupConfig",
    "CommandEntry",
    "MatchedHandlerInfo",
    "PluginCommandSummary",
    "get_config",
    "init_config",
    "refresh_config",
    "save_custom_groups_to_storage",
    "update_custom_groups_in_config",
    # Infrastructure
    "logger",
    "get_logger",
    "set_context",
    "get_context",
    "clear_context",
    "init_plugin_paths",
    "get_plugin_dir",
    "get_data_dir",
    "get_plugin_data_dir",
    "get_cache_dir",
    "get_custom_groups_path",
    "CommandIndex",
    "get_command_index",
    "reset_command_index",
    "invalidate_command_cache",
    "CommandExecutor",
    "get_command_executor",
    # Application
    "HelpService",
    "CustomGroupService",
    "get_custom_group_service",
    "get_help_service",
    "init_plugin_service",
    "reset_help_service",
    "reset_custom_group_service",
    "SearchCommandResponse",
    "CommandDetailResponse",
    "ExecuteCommandResponse",
    "ListCustomGroupsResponse",
]
